name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'patch'

jobs:
  up-version:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checout
        uses: actions/checkout@v2
      - name: Set Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Up Version
        run: |
          echo "${{github.event.inputs.version}}"
          git config user.name "GitHub Action"
          yarn version --${{github.event.inputs.version}}
      - name: Set Version
        id: version
        run: echo ""::set-output name=version::$(npx -c 'echo "$npm_package_version"')""
      - name: Foo
        run: |
          yarn version --new-version ${{steps.version.outputs.version}}
          git tag
          # git push origin v${{npm view . version}}
